import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b bg-white/80 px-4 py-3 shadow-sm backdrop-blur dark:bg-neutral-900/80">
          <nav className="mx-auto flex max-w-6xl items-center gap-6 text-sm font-medium text-neutral-800 dark:text-neutral-100">
            <Link href="/" className="hover:text-blue-600">
              Bosh sahifa
            </Link>
            <Link href="/articles/preview" className="hover:text-blue-600">
              Maqolalar
            </Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
